-- V1.0.0

PROMPT "Création de la base de données Tenrac";

-- **************************************************************************** Définition des données

PROMPT "Définition des données";

DROP TABLE IF EXISTS Ordre_tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Club_tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Grade CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Rand CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Titre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Dignite CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Plat CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Aliment CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Type CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Croyance CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OpposistionConvictionPerso CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Sauce CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Machine CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Certificat CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Historique CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Restaurant CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Cuisinier CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Organisme_Associe CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Croisade CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Ingredient CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Fabriquant CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Raclette CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Legume CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Carte_membre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Groupe_membre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Repas CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Allergie CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Registre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_compose_de CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Provoque CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Heurte CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_accompagne CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Commande CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Federe CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Valide CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS A CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Sert CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_un_assemblage CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_fabrique CASCADE CONSTRAINTS PURGE;

CREATE TABLE Ordre_tenrac (
	idOT NUMBER(10),
	nom VARCHAR2(20) NOT NULL, 
	adresse VARCHAR2(15) NOT NULL, 
	ville VARCHAR2(15) NOT NULL,
	codepostale NUMBER(1, 0) NOT NULL, 
	CONSTRAINT pk_Ordre_tenrac PRIMARY KEY (idOT),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
	CONSTRAINT ch_Etudiant_typeBac CHECK (typeBac IN ('GENERAL', 'TECHNOLOGIQUE', 'INTERNATIONAL')),
	CONSTRAINT ch_Etudiant_groupe CHECK (groupe BETWEEN 1 AND 4)
);

CREATE TABLE Club_tenrac (
	idCT NUMBER(10),
	nom VARCHAR2(20) NOT NULL, 
	adresse VARCHAR2(15) NOT NULL, 
	ville VARCHAR2(15) NOT NULL,
	territoire VARCHAR2(50) NOT NULL, 
	CONSTRAINT pk_Club_tenrac PRIMARY KEY (idCT),
	CONSTRAINT uk_Club_tenrac_01 UNIQUE (nom, prenom),
	CONSTRAINT ch_Etudiant_typeBac CHECK (typeBac IN ('GENERAL', 'TECHNOLOGIQUE', 'INTERNATIONAL')),
	CONSTRAINT ch_Etudiant_groupe CHECK (groupe BETWEEN 1 AND 4)
);

CREATE TABLE Grade (
	idG NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (idG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);

CREATE TABLE RANG (
	idR NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Rang PRIMARY KEY (IdR),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Titre (
	idT NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Titre PRIMARY KEY (IdT),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Dignite (
	idD NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Dignite PRIMARY KEY (IdD),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Plat (
	idP NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Plat PRIMARY KEY (IdP),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Aliment (
	idA NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	taille VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Aliment PRIMARY KEY (IdA),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Type (
	idTy NUMBER(10),
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (IdT),
);
CREATE TABLE Croyance (
	idC NUMBER(10),
	dieuTenrac VARCHAR2(50) NOT NULL, 
	dieuDesTenders VARCHAR2(50) NOT NULL, 
	dieuDeLaRaclette VARCHAR2(50) NOT NULL,
    dieuDesLégumes VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Croyance PRIMARY KEY (IdC),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE OpposistionConvictionPerso (
	idOCP NUMBER(10),
	politique VARCHAR2(50) NOT NULL, 
	ethnique VARCHAR2(50) NOT NULL, 
	chocDesCultures VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_OpposistionConvictionPerso PRIMARY KEY (IdGOCP),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Sauce (
	idS NUMBER(10),
	type VARCHAR2(50) NOT NULL, 
	nom VARCHAR2(50) NOT NULL, 
	CONSTRAINT pk_Sauce PRIMARY KEY (IdS),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Machine (
	idM NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	modele VARCHAR2(50) NOT NULL, 
	prix VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Machine PRIMARY KEY (IdM),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Certificat (
	idC NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	dateDep DATE NOT NULL,
    dateFin VARCHAR2(50) NOT NULL ,
	CONSTRAINT pk_Certificat PRIMARY KEY (IdC),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Historique (
	idH NUMBER(10),
	date_ DATE,
	CONSTRAINT pk_Historique PRIMARY KEY (IdH),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Restaurant (
	IdR NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	ville VARCHAR2(50) NOT NULL, 
	adresse VARCHAR2(50) NOT NULL,
    type VARCHAR2(50) NOT NULL, 
	lieu VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Cuisinier (
	idCu NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	prenom VARCHAR2(50), 
	age VARCHAR2(50) NOT NULL,
    adresse VARCHAR2(50) NOT NULL ,
	CONSTRAINT pk_Cuisinier PRIMARY KEY (Id_Cuisinier),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Organisme_Associe (
	idOA NUMBER(10),
	nomEntreprise VARCHAR2(50) NOT NULL, 
	type VARCHAR2(50) NOT NULL, 
	adresse VARCHAR2(50) NOT NULL,
	ville VARCHAR2(50) NOT NULL,
	codePostale VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_OA PRIMARY KEY (IdOA),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Croisade (
	idCr NUMBER(10),
	duree TIMESTAMP NOT NULL, 
	dateDep DATE NOT NULL, 
	nom VARCHAR2(50) NOT NULL,
    dateFin DATE NOT NULL,
    type VARCHAR2(50) NOT NULL,
    nom VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Croisade PRIMARY KEY (idCr),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Ingredient (
	type VARCHAR2(50) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL, 
	nom VARCHAR2(50) NOT NULL,
);
CREATE TABLE Fabriquant (
	idF NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	prenom VARCHAR2(50) NOT NULL, 
	adresse VARCHAR2(50) NOT NULL,
    codePostale NUMBER(10) NOT NULL, 
	ville VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Fabriquant PRIMARY KEY (idF),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Raclette (
	idRa NUMBER(10),
	type VARCHAR2(50) NOT NULL,
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Legume (
	type VARCHAR2(50) NOT NULL, 
	nom VARCHAR2(50) NOT NULL, 
	taille NUMBER(3) NOT NULL, 
	libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Tenrac (
	IdG NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	prenom VARCHAR2(50) NOT NULL, 
	age NUMBER(10) NOT NULL,
    adresse VARCHAR2(50) NOT NULL ,
    courriel VARCHAR2(50) NOT NULL, 
	numTel NUMBER(10) NOT NULL,
    adressePostale NUMBER(10) NOT NULL ,
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Carte_membre (
	RFID NUMBER(10) NOT NULL, 
	numCode NUMBER(10) NOT NULL, 
	numClub NUMBER(10) NOT NULL,
    numSIRET NUMBER(10) NOT NULL, 
	raisonSociale VARCHAR2(50) NOT NULL,
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Groupe_membre (
	date_ DATE NOT NULL, 
	adressePartenaire VARCHAR2(50) NOT NULL, 
	Libelle VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Repas (
	idRep NUMBER(10),
	nomPlat VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_Repas PRIMARY KEY (idRep),
);
CREATE TABLE Allergie (
	idAl NUMBER(10),
	nom VARCHAR2(50) NOT NULL, 
	CONSTRAINT pk_Aliment PRIMARY KEY (idAl),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Registre (
	idRe NUMBER(10),
	Statut VARCHAR2(50) NOT NULL, 
	Date_ TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_Registre PRIMARY KEY (idRe),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Est_compose_de (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Provoque (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Heurte (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Est_accompagne (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Commande (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);

CREATE TABLE Federe (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Valide (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE A (
	CONSTRAINT pk_Grade PRIMARY KEY (IdG),
	CONSTRAINT uk_Etudiant_01 UNIQUE (nom, prenom),
);
CREATE TABLE Sert (
	CONSTRAINT fk_id_Repas FOREIGN KEY (idRep) REFERENCES Repas(idRep),
    CONSTRAINT fk_id_Cuisinier FOREIGN KEY (idC) REFERENCES Cuisinier(idC),
    CONSTRAINT fk_id_Restaurant FOREIGN KEY (idRes) REFERENCES Restaurant(idRes),
);
CREATE TABLE Est_un_assemblage (
	CONSTRAINT fk_id_Sauce FOREIGN KEY (idS) REFERENCES Sauce(idS),
    CONSTRAINT fk_id_Aliment FOREIGN KEY (idA) REFERENCES Ingredient(idA),
);
CREATE TABLE Est_fabrique (
	CONSTRAINT fk_id_Machine FOREIGN KEY (idM) REFERENCES Machine(idM),
    CONSTRAINT fk_id_Fabriquant FOREIGN KEY (idF) REFERENCES Fabriquant(idF),
);