-- V1.0.0

PROMPT "Création de la base de données Tenrac";

-- **************************************************************************** Définition des données

PROMPT "Définition des données";

DROP TABLE IF EXISTS Ordre_tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Club_tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Grade CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Rand CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Titre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Dignite CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Plat CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Aliment CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Type CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Croyance CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OpposistionConvictionPerso CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Sauce CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Machine CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Entretien CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Certificat CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Historique CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Restaurant CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Cuisinier CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Organisme_Associe CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Croisade CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Ingredient CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Fabriquant CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Raclette CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Legume CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Tenrac CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Carte_membre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Groupe_membre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Repas CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Allergie CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Registre CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_compose_de CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Provoque CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Heurte CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_accompagne CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Commande CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Federe CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Valide CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS A CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Sert CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_un_assemblage CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS Est_fabrique CASCADE CONSTRAINTS PURGE;


CREATE TABLE ORDRE_TENRAC(
   idOT NUMBER(10),
   nom VARCHAR2(50),
   adresse VARCHAR2(50),
   ville VARCHAR2(50),
   type VARCHAR2(50),
   codePostale NUMBER(10),
   PRIMARY KEY(idOT)
);

CREATE TABLE CLUB_TENRAC(
   idCT NUMBER(10),
   nom VARCHAR2(50),
   adresse VARCHAR2(50),
   type VARCHAR2(50),
   ville VARCHAR2(50),
   territoire VARCHAR2(50),
   PRIMARY KEY(idCT)
);

CREATE TABLE GRADE(
   idG NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   PRIMARY KEY(idG)
);

CREATE TABLE RANG(
   idR NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   PRIMARY KEY(idR)
);

CREATE TABLE TITRE(
   idT NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   ibelle VARCHAR2(50),
   PRIMARY KEY(IdT)
);

CREATE TABLE DIGNITE(
   idD NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   PRIMARY KEY(idD)
);

CREATE TABLE PLAT(
   idP NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   PRIMARY KEY(idP)
);

CREATE TABLE ALIMENT(
   idA NUMBER(10),
   nom VARCHAR2(50),
   taille NUMBER(3),
   PRIMARY KEY(idA)
);

CREATE TABLE TYPE(
   idTy NUMBER(10),
   libelle VARCHAR2(50),
   PRIMARY KEY(idTy)
);

CREATE TABLE CROYANCE(
   idC NUMBER(10),
   dieuTenrac VARCHAR2(50),
   dieuDesTenders VARCHAR2(50),
   dieuDeLaRaclette VARCHAR2(50),
   dieuDesL gumes VARCHAR2(50),
   PRIMARY KEY(idC)
);

CREATE TABLE OppositionConvictionPerso(
   idOCP NUMBER(10),
   politique VARCHAR2(50),
   ethnique VARCHAR2(50),
   chocDesCultures VARCHAR2(50),
   PRIMARY KEY(idOCP)
);

CREATE TABLE SAUCE(
   idSa NUMBER(10),
   type VARCHAR2(50),
   nom VARCHAR2(50),
   PRIMARY KEY(idSa)
);

CREATE TABLE MACHINE(
   idM NUMBER(10),
   nom VARCHAR2(50),
   modele VARCHAR2(50),
   prix VARCHAR2(50),
   PRIMARY KEY(IdM)
);

CREATE TABLE ENTRETIEN(
   idE NUMBER(10),
   nom VARCHAR2(50),
   modele VARCHAR2(50),
   prix VARCHAR2(50),
   PRIMARY KEY(IdM)
);

CREATE TABLE CERTIFICAT(
   idM NUMBER(10),
   nom VARCHAR2(50),
   type VARCHAR2(50),
   dateDep DATE,
   dateFin VARCHAR2(50),
   PRIMARY KEY(idM),
   FOREIGN KEY(idM) REFERENCES MACHINE(idM)
);

CREATE TABLE HISTORIQUE(
   idH NUMBER(10),
   date_ DATE,
   PRIMARY KEY(idH)
);

CREATE TABLE RESTAURANT(
   idR NUMBER(10),
   nom VARCHAR2(50),
   ville VARCHAR2(50),
   adresse VARCHAR2(50),
   type VARCHAR2(50),
   ieu VARCHAR2(50),
   PRIMARY KEY(idR)
);

CREATE TABLE CUISINIER(
   idCu NUMBER(10),
   nom VARCHAR2(50),
   prenom VARCHAR2(50),
   age VARCHAR2(50),
   adresse VARCHAR2(50),
   PRIMARY KEY(idCu)
);

CREATE TABLE Organisme_Associ (
   idOA NUMBER(10),
   nomEntreprise VARCHAR2(50),
   type VARCHAR2(50),
   adresse VARCHAR2(50),
   ville VARCHAR2(50),
   codePostale NUMBER(10),
   PRIMARY KEY(idOA)
);

CREATE TABLE CROISADE(
   idCa NUMBER(10),
   duree TIMESTAMP,
   dateDep DATE,
   nom VARCHAR2(50),
   dateFin DATE,
   type VARCHAR2(50),
   idC NUMBER(10) NOT NULL,
   idOCP NUMBER(10) NOT NULL,
   PRIMARY KEY(idCa),
   FOREIGN KEY(idCa) REFERENCES CROYANCE(idC),
   FOREIGN KEY(idOCP) REFERENCES OppositionConvictionPerso(idOCP)
);

CREATE TABLE INGREDIENT(
   idAl NUMBER(10),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   nom VARCHAR2(50),
   PRIMARY KEY(idAl),
   FOREIGN KEY(idAl) REFERENCES ALIMENT(idAl)
);

CREATE TABLE FABRIQUANT(
   idF NUMBER(10),
   Nom VARCHAR2(50),
   prenom VARCHAR2(50),
   adresse VARCHAR2(50),
   codePostale NUMBER(10),
   ville VARCHAR2(50),
   PRIMARY KEY(idF)
);

CREATE TABLE RACLETTE(
   idRa NUMBER(10),
   type VARCHAR2(50),
   libelle VARCHAR2(50),
   idP NUMBER(10) NOT NULL,
   idAl NUMBER(10) NOT NULL,
   PRIMARY KEY(idRRa),
   FOREIGN KEY(idP) REFERENCES PLAT(idP),
   FOREIGN KEY(idAl) REFERENCES ALIMENT(idAl)
);

CREATE TABLE LEGUME(
   idAl NUMBER(10),
   type VARCHAR2(50),
   nom VARCHAR2(50),
   taille VARCHAR2(50),
   PRIMARY KEY(idAl),
   FOREIGN KEY(idAl) REFERENCES ALIMENT(idAl)
);

CREATE TABLE TENRAC(
   idTe NUMBER(10),
   nom VARCHAR2(50),
   prenom VARCHAR2(50),
   age NUMBER(10),
   adresse VARCHAR2(50),
   courriel VARCHAR2(50),
   numTel NUMBER(10),
   adressePostale NUMBER(10),
   idG NUMBER(10) NOT NULL,
   idOT NUMBER(10),
   idCT NUMBER(10),
   idD NUMBER(10) NOT NULL,
   idT NUMBER(10) NOT NULL,
   Id_Rang NUMBER(10) NOT NULL,
   PRIMARY KEY(Id_Tenrac),
   UNIQUE(Id_Dignite),
   UNIQUE(Id_Titre),
   UNIQUE(Id_Rang),
   FOREIGN KEY(idG) REFERENCES GRADE(idG),
   FOREIGN KEY(idOT) REFERENCES ORDRE_TENRAC(idOT),
   FOREIGN KEY(idCT) REFERENCES CLUB_TENRAC(Id_ClubTenrac),
   FOREIGN KEY(Id_Dignite) REFERENCES DIGNITE(idD),
   FOREIGN KEY(Id_Titre) REFERENCES TITRE(Id_Titre),
   FOREIGN KEY(Id_Rang) REFERENCES RANG(Id_Rang)
);

CREATE TABLE CARTE_MEMBRE(
   Id_Tenrac NUMBER(10),
   RFID NUMBER(10) NOT NULL,
   numCode NUMBER(10) NOT NULL,
   numClub NUMBER(10) NOT NULL,
   numSIRET NUMBER(10) NOT NULL,Id_OrdreTenrac
   raisonSociale VARCHAR2(50),
   Id_ClubTenrac NUMBER(10) NOT NULL,
   Id_OrganismeAssocie NUMBER(10) NOT NULL,
   PRIMARY KEY(Id_Tenrac),
   UNIQUE(RFID),
   UNIQUE(numCode),
   UNIQUE(numClub),
   UNIQUE(numSIRET),
   FOREIGN KEY(Id_Tenrac) REFERENCES TENRAC(Id_Tenrac),
   FOREIGN KEY(Id_ClubTenrac) REFERENCES CLUB_TENRAC(Id_ClubTenrac),
   FOREIGN KEY(Id_OrganismeAssocie) REFERENCES Organisme_Associ (Id_OrganismeAssocie)
);

CREATE TABLE GROUPE_TENRAC(
   Id_Tenrac NUMBER(10),
   Date_ DATE,
   Adresse_Partenaire VARCHAR2(50),
   PRIMARY KEY(Id_Tenrac),
   FOREIGN KEY(Id_Tenrac) REFERENCES TENRAC(Id_Tenrac)
);

CREATE TABLE REPAS(
   Id_Repas NUMBER(10),
   IntitulePlat VARCHAR2(50),
   Id_Machine NUMBER(10) NOT NULL,
   PRIMARY KEY(Id_Repas),
   FOREIGN KEY(Id_Machine) REFERENCES MACHINE(Id_Machine)
);

CREATE TABLE ALLERGIE(
   id_Allergie NUMBER(10),
   Nom VARCHAR2(50),
   idTy NUMBER(10) NOT NULL,
   PRIMARY KEY(idAll),
   FOREIGN KEY(idTy) REFERENCES TYPE(idTy),
);

CREATE TABLE REGISTRE(
   idRe NUMBER(10),
   statut VARCHAR2(50),
   date_ TIMESTAMP WITH TIME ZONE,
   idOT NUMBER(10) NOT NULL,
    NUMBER(10) NOT NULL,
   Id_Tenrac NUMBER(10) NOT NULL,
   Id_Machine NUMBER(10) NOT NULL,
   Id_Historique NUMBER(10) NOT NULL,
   PRIMARY KEY(Id_Registre),
   UNIQUE(Id_OrdreTenrac),
   FOREIGN KEY(Id_OrdreTenrac) REFERENCES ORDRE_TENRAC(Id_OrdreTenrac),
   FOREIGN KEY(Id_ClubTenrac) REFERENCES CLUB_TENRAC(Id_ClubTenrac),
   FOREIGN KEY(Id_Tenrac) REFERENCES TENRAC(Id_Tenrac),
   FOREIGN KEY(Id_Machine) REFERENCES MACHINE(Id_Machine),
   FOREIGN KEY(Id_Historique) REFERENCES HISTORIQUE(Id_Historique)
);

CREATE TABLE EST_COMPOSE_DE(
   Id_Repas NUMBER(10),
   Id_Plat NUMBER(10),
   PRIMARY KEY(Id_Repas, Id_Plat),
   FOREIGN KEY(Id_Repas) REFERENCES REPAS(Id_Repas),
   FOREIGN KEY(Id_Plat) REFERENCES PLAT(Id_Plat)
);

CREATE TABLE PROVOQUE(
   Id_Aliment NUMBER(10),
   Id_Allergie NUMBER(10),
   PRIMARY KEY(Id_Aliment, Id_Allergie),
   FOREIGN KEY(Id_Aliment) REFERENCES ALIMENT(Id_Aliment),
   FOREIGN KEY(Id_Allergie) REFERENCES ALLERGIE(Id_Allergie)
);

CREATE TABLE HEURTE(
   Id_Aliment NUMBER(10),
   Id_Croyance NUMBER(10),
   Id_OppositionConvictionPerso NUMBER(10),
   PRIMARY KEY(Id_Aliment, Id_Croyance, Id_OppositionConvictionPerso),
   FOREIGN KEY(Id_Aliment) REFERENCES ALIMENT(Id_Aliment),
   FOREIGN KEY(Id_Croyance) REFERENCES CROYANCE(Id_Croyance),
   FOREIGN KEY(Id_OppositionConvictionPerso) REFERENCES OppositionConvictionPerso(Id_OppositionConvictionPerso)
);

CREATE TABLE EST_ACCOMPAGNE_DE(
   Id_Plat NUMBER(10),
   Id_Sauce NUMBER(10),
   PRIMARY KEY(Id_Plat, Id_Sauce),
   FOREIGN KEY(Id_Plat) REFERENCES PLAT(Id_Plat),
   FOREIGN KEY(Id_Sauce) REFERENCES SAUCE(Id_Sauce)
);

CREATE TABLE COMMANDE(
   Id_Tenrac NUMBER(10),
   Id_Repas NUMBER(10),
   PRIMARY KEY(Id_Tenrac, Id_Repas),
   FOREIGN KEY(Id_Tenrac) REFERENCES GROUPE_TENRAC(Id_Tenrac),
   FOREIGN KEY(Id_Repas) REFERENCES REPAS(Id_Repas)
);

CREATE TABLE FEDERE(
   Id_OrdreTenrac NUMBER(10),
   Id_ClubTenrac NUMBER(10),
   PRIMARY KEY(Id_OrdreTenrac, Id_ClubTenrac),
   FOREIGN KEY(Id_OrdreTenrac) REFERENCES ORDRE_TENRAC(Id_OrdreTenrac),
   FOREIGN KEY(Id_ClubTenrac) REFERENCES CLUB_TENRAC(Id_ClubTenrac)
);

CREATE TABLE VALIDE(
   Id_Tenrac NUMBER(10),
   Id_Machine NUMBER(10),
   PRIMARY KEY(Id_Tenrac, Id_Machine),
   FOREIGN KEY(Id_Tenrac) REFERENCES TENRAC(Id_Tenrac),
   FOREIGN KEY(Id_Machine) REFERENCES MACHINE(Id_Machine)
);

CREATE TABLE A(
   Id_Machine NUMBER(10),
   Id_Historique NUMBER(10),
   PRIMARY KEY(Id_Machine, Id_Historique),
   FOREIGN KEY(Id_Machine) REFERENCES CERTIFICAT(Id_Machine),
   FOREIGN KEY(Id_Historique) REFERENCES HISTORIQUE(Id_Historique)
);

CREATE TABLE SERT(
   Id_Repas NUMBER(10),
   Id_Cuisinier NUMBER(10),
   Id_Restaurant NUMBER(10),
   PRIMARY KEY(Id_Repas, Id_Cuisinier, Id_Restaurant),
   FOREIGN KEY(Id_Repas) REFERENCES REPAS(Id_Repas),
   FOREIGN KEY(Id_Cuisinier) REFERENCES CUISINIER(Id_Cuisinier),
   FOREIGN KEY(Id_Restaurant) REFERENCES RESTAURANT(Id_Restaurant)
);

CREATE TABLE EST_UN_ASSEMBLAGE(
   idS NUMBER(10),
   Id_Aliment NUMBER(10),
   PRIMARY KEY(Id_Sauce, Id_Aliment),
   FOREIGN KEY(Id_Sauce) REFERENCES SAUCE(Id_Sauce),
   FOREIGN KEY(Id_Aliment) REFERENCES INGREDIENT(Id_Aliment)
);

CREATE TABLE EST_FABRIQUE(
   Id_Machine NUMBER(10),
   Id_Fabriquant NUMBER(10),
   PRIMARY KEY(Id_Machine, Id_Fabriquant),
   FOREIGN KEY(Id_Machine) REFERENCES MACHINE(Id_Machine),
   FOREIGN KEY(Id_Fabriquant) REFERENCES FABRIQUANT(Id_Fabriquant)
);

